import './bootstrap-vue'
import './remixicon.js'
import '../assets/scss/style.scss'
import './sweet-alert.js'
import './toastr.js'
import './apexchart.js'
import './validator.js'
import './vue-editor.js'
// import './font-awesome.js'
